# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|


  # config.vm.box = "generic/ubuntu1804"
  # config.vm.box = "generic/ubuntu2004"
  # config.vm.box = "custv1u"
  # config.vm.box = "1804-u3"
  config.vm.box = "2004-u1"
  
  config.vm.provider "libvirt" do |vb|

    vb.memory = "4028"
    vb.cpus = "2"
    # vb.gui = true
  end


  config.vm.define "node1" do |node1|
    node1.vm.hostname = "node1"
    node1.vm.network "private_network", ip: "10.10.1.4"
  #   # node1.vm.network "public_network", ip: "192.168.0.50", bridge: "eno1", dev: "eno1"
  #   # node1.vm.provision :shell, inline: "echo 'source /home/vagrant/vagrant_data/env/bootenv.sh' > /etc/profile.d/sa-environment.sh", :run => 'always'
  end
  # config.vm.provision :shell, inline: "echo 'source /home/vagrant/vagrant_data/env/bootenv.sh' > /etc/profile.d/sa-environment.sh", :run => 'always'


  config.vm.define "node2" do |node2|
    node2.vm.hostname = "node2"
    node2.vm.network "private_network", ip: "10.10.1.5"
  end

  config.vm.define "node3" do |node3|
    node3.vm.hostname = "node3"
    node3.vm.network "private_network", ip: "10.10.1.6"
  end


# comment out when versioning with updated box
  config.ssh.username = 'ubuntu'
  config.vm.synced_folder "/home/bilal/ABC-Shares/vagrant", "/home/ubuntu/vagrant_data", type: "nfs", mount_options: ["vers=3,tcp"]

  # config.vm.synced_folder "/home/bilal/ABC-Shares/vagrant", "/home/vagrant/vagrant_data", type: "nfs", mount_options: ["vers=3,tcp"]  
  config.ssh.insert_key = false
  config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '/home/bilal/.ssh/id_rsa']
  config.vm.provision "file", source: "/home/bilal/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
  config.vm.provision "file", source: "/home/bilal/.ssh/id_rsa", destination: "~/.ssh/id_rsa"
  config.vm.synced_folder '.', '/vagrant', disabled: true

  # config.vm.network "public_network"

  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box_check_update = false


  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
#  config.vm.box = "generic/ubuntu1804"
#  config.vm.box = "hashicorp/bionic64"
#  config.vm.provider "vmware_desktop"
  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "private_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.
  # config.vm.provider "virtualbox" do |vb|

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
#  config.vm.provider "vmware_desktop" do |v|
#    v.gui = true

#  end
end
