---
apiVersion: v1
kind: Namespace
metadata:
  name: ragnar
---
apiVersion: v1
kind: Secret
metadata:
  name: ragnar
  namespace: ragnar
stringData:
  NODE_ENV: development
  DB_RAGNAR_HOST: mysql-primary-headless.mysql
  DB_RAGNAR_NAME: ragnar
---
apiVersion: v1
kind: Secret
metadata:
  name: planb
  namespace: ragnar
stringData:
  # NODE_ENV: development
  # DB_RAGNAR_HOST: mysql-primary-headless.mysql
  # DB_RAGNAR_NAME: ragnar
  # DB_RAGNAR_PASSWD: porcupinetreevoyage34
  # DB_RAGNAR_USER: root
  DB_ZABBIX_HOST: zabbix_db
  DB_ZABBIX_NAME: ragnar
  DB_ZABBIX_PASSWD: password
  DB_ZABBIX_USER: user
  # MASTER_NAME: OCRM-Q-Primary
  # REDIS_HOST_1: redis-headless.redis

